---
# roles/workstation/tasks/main.yml
  - name: add timezone configuration
    command: bash -c 'echo US/Eastern > /etc/timezone'

  - name: add kernel parameters to /etc/sysctl.d/60-custom.conf
    blockinfile: |
      dest=/etc/sysctl.d/60-custom.conf
      create=yes
      content="# Auto-reboot linux 10 seconds after a kernel panic
        kernel.panic = 10
        kernel.panic_on_oops = 10
        kernel.unknown_nmi_panic = 10
        kernel.panic_on_unrecovered_nmi = 10
        kernel.panic_on_io_nmi = 10
        # Controls whether core dumps will append the PID to the core filename, useful for debugging multi-threaded applications
        kernel.core_uses_pid = 1
        # Turn on address space randomization - security is super important
        kernel.randomize_va_space = 2
        vm.swappiness = 0
        vm.dirty_ratio = 80
        vm.dirty_background_ratio = 5
        vm.dirty_expire_centisecs = 12000
        vm.overcommit_memory = 1
        # ------ VM ------
        fs.file-max = 204708
        #fs.epoll.max_user_instances = 4096
        fs.suid_dumpable = 0
        # ------ NETWORK SECURITY ------
        # Turn on protection for bad icmp error messages
        net.ipv4.icmp_ignore_bogus_error_responses = 1
        # Turn on syncookies for SYN flood attack protection
        net.ipv4.tcp_syncookies = 1
        net.ipv4.tcp_max_syn_backlog = 8096
        net.ipv4.tcp_synack_retries = 2
        net.ipv4.tcp_syn_retries = 2
        # Log suspicious packets, such as spoofed, source-routed, and redirect
        net.ipv4.conf.all.log_martians = 1
        net.ipv4.conf.default.log_martians = 1
        # Disables these ipv4 features, not very legitimate uses
        net.ipv4.conf.all.accept_source_route = 0
        net.ipv4.conf.default.accept_source_route = 0
        # ------ NETWORK PERFORMANCE ------
        # Netflix 2014 recommendations
        net.core.netdev_max_backlog = 5000
        net.core.rmem_max = 16777216
        net.core.wmem_max = 16777216
        net.ipv4.tcp_wmem = 4096 12582912 16777216
        net.ipv4.tcp_rmem = 4096 12582912 16777216
        # Allow reusing sockets in TIME_WAIT state for new connections
        net.ipv4.tcp_tw_reuse = 1
        # Socket max connections waiting to get accepted; the listen() backlog.
        # Default is 128.
        net.core.somaxconn = 4096
        # Decrease fin timeout. After telling the client we are closing, how long to wait for a FIN, ACK?
        # Default is 60.
        net.ipv4.tcp_fin_timeout = 10
        # Avoid falling back to slow start after a connection goes idle
        # keeps our cwnd large with the keep alive connections
        net.ipv4.tcp_slow_start_after_idle = 0"

  - name: reload sysctl kernel parameter settings
    command: bash -c 'sysctl -p /etc/sysctl.d/60-custom.conf'

  - name: copy swapfile init script
    copy:  src=aws-swap-init dest=/etc/init.d/aws-swap-init mode=0755

  - name: register swapfile init script
    command: bash -c 'update-rc.d aws-swap-init defaults'

  - name: add entries to sudoers
    lineinfile: |
      dest=/etc/sudoers.d/90-cloud-init-users
      line="luke ALL=(ALL) NOPASSWD:ALL"

  - name: add luke user account
    user: name=luke uid=1001 comment="Luke Youngblood" createhome=yes shell=/bin/bash

  - name: accept Oracle license part 1
    command: bash -c 'echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections'

  - name: accept Oracle license part 2
    command: bash -c 'echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections'

  - name: Update apt cache
    apt: update_cache=yes

  - name: Add apt key for ubuntu
    apt_key: keyserver=keyserver.ubuntu.com id=E56151BF

  - name: Determine Linux distribution distributor
    shell: lsb_release -is | tr ''[:upper:]'' ''[:lower:]''
    register: release_distributor

  - name: Determine Linux distribution codename
    command: lsb_release -cs
    register: release_codename

  - name: Add Mesosphere repository to sources list
    lineinfile: >
      dest=/etc/apt/sources.list.d/mesosphere.list
      line="deb http://repos.mesosphere.io/{{ release_distributor.stdout }} {{ release_codename.stdout }} main"
      mode=0644
      create=yes

  - name: Add java apt repository
    apt_repository: repo='ppa:webupd8team/java'

  - name: Add Google Chrome key
    shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -

  - name: Add Google Chrome repo
    copy: >
      content="deb http://dl.google.com/linux/chrome/deb/ stable main"
      dest="/etc/apt/sources.list.d/google-chrome.list"
      owner=root
      group=root
      mode=0644

  - name: Update apt cache
    apt: update_cache=yes

  - name: Install packages
    apt: pkg={{ item }} state=installed
    with_items: 
      - nfs-common
      - oracle-java8-installer
      - liblapack-dev
      - libblas-dev
      - gfortran
      - ntp
      - vnc4server 
      - xfce4 
      - xfce4-goodies 
      - emacs 
      - firefox 
      - git 
      - maven 
      - npm 
      - python-pip 
      - clusterssh
      - graphviz
      - google-chrome-stable
      - python-numpy
      - python-scipy
      - python-dev
      - python-nose
      - g++
      - libopenblas-dev

  - name: Install boto and run setup
    command: bash -c 'git clone git://github.com/boto/boto.git;cd /home/ubuntu/boto;python setup.py install'
    args:
      chdir: /home/ubuntu

  - name: Install bower
    command: bash -c 'npm install -g bower'

  - name: Install Theano
    command: bash -c 'pip install Theano'

  - name: Update all packages to the latest version
    apt: upgrade=dist

  - name: Create nodejs symlink
    file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

  - name: execute dpkg-reconfigure
    command: "dpkg-reconfigure -f noninteractive tzdata"