---
# roles/delete-old-launch-configurations/tasks/main.yml

- lc_find:
    region: "{{ region }}"
    name_regex: "{{ asg_name }}-.*"
    sort: yes
    sort_end: -5
  register: old_lc_result

- ec2_lc:
    region: "{{ region }}"
    name: "{{ item.name }}"
    state: absent
  with_items: old_lc_result.results
  ignore_errors: yes