---
# roles/worker-delete-old-amis/tasks/main.yml

- ec2_ami_find:
    region: "{{ region }}"
    owner: self
    name: "{{ asg_name }}-*"
    sort: name
    sort_end: -5
  register: old_ami_result

- ec2_ami:
    region: "{{ region }}"
    image_id: "{{ item.ami_id }}"
    delete_snapshot: yes
    state: absent
  with_items: old_ami_result.results
  ignore_errors: yes